name-template: "v$RESOLVED_VERSION"
tag-template:    "v$RESOLVED_VERSION"
version-resolver:
  major: { labels: ["major"] }
  minor: { labels: ["minor"] }
  patch: { labels: ["patch", "dependencies"] }
  default: patch
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
exclude-labels:
  - skip-changelog
template: |
  ## Changes
  $CHANGES
