# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import amdi_pb2 as amdi__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in amdi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentIntelligenceStub:
    """=============================================================================
    ============================== SERVICES =====================================
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
                '/amdi.v1.DocumentIntelligence/Upload',
                request_serializer=amdi__pb2.UploadRequest.SerializeToString,
                response_deserializer=amdi__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/amdi.v1.DocumentIntelligence/GetJob',
                request_serializer=amdi__pb2.GetJobRequest.SerializeToString,
                response_deserializer=amdi__pb2.Job.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/amdi.v1.DocumentIntelligence/CancelJob',
                request_serializer=amdi__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=amdi__pb2.Job.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/amdi.v1.DocumentIntelligence/ListJobs',
                request_serializer=amdi__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=amdi__pb2.ListJobsResponse.FromString,
                _registered_method=True)
        self.StreamJobEvents = channel.unary_stream(
                '/amdi.v1.DocumentIntelligence/StreamJobEvents',
                request_serializer=amdi__pb2.GetJobRequest.SerializeToString,
                response_deserializer=amdi__pb2.JobEvent.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/amdi.v1.DocumentIntelligence/Query',
                request_serializer=amdi__pb2.QueryRequest.SerializeToString,
                response_deserializer=amdi__pb2.RetrievalResult.FromString,
                _registered_method=True)
        self.ExportTokenOptimized = channel.unary_unary(
                '/amdi.v1.DocumentIntelligence/ExportTokenOptimized',
                request_serializer=amdi__pb2.ExportRequest.SerializeToString,
                response_deserializer=amdi__pb2.TokenOptimizedExport.FromString,
                _registered_method=True)
        self.PiiScan = channel.unary_unary(
                '/amdi.v1.DocumentIntelligence/PiiScan',
                request_serializer=amdi__pb2.PiiScanRequest.SerializeToString,
                response_deserializer=amdi__pb2.PiiScanResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/amdi.v1.DocumentIntelligence/Health',
                request_serializer=amdi__pb2.HealthRequest.SerializeToString,
                response_deserializer=amdi__pb2.HealthResponse.FromString,
                _registered_method=True)


class DocumentIntelligenceServicer:
    """=============================================================================
    ============================== SERVICES =====================================
    =============================================================================

    """

    def Upload(self, request_iterator, context):
        """---- Documents ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """---- Jobs ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """---- Retrieval ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportTokenOptimized(self, request, context):
        """---- Export ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PiiScan(self, request, context):
        """---- Compliance ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """---- Health ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentIntelligenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=amdi__pb2.UploadRequest.FromString,
                    response_serializer=amdi__pb2.UploadResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=amdi__pb2.GetJobRequest.FromString,
                    response_serializer=amdi__pb2.Job.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=amdi__pb2.CancelJobRequest.FromString,
                    response_serializer=amdi__pb2.Job.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=amdi__pb2.ListJobsRequest.FromString,
                    response_serializer=amdi__pb2.ListJobsResponse.SerializeToString,
            ),
            'StreamJobEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobEvents,
                    request_deserializer=amdi__pb2.GetJobRequest.FromString,
                    response_serializer=amdi__pb2.JobEvent.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=amdi__pb2.QueryRequest.FromString,
                    response_serializer=amdi__pb2.RetrievalResult.SerializeToString,
            ),
            'ExportTokenOptimized': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportTokenOptimized,
                    request_deserializer=amdi__pb2.ExportRequest.FromString,
                    response_serializer=amdi__pb2.TokenOptimizedExport.SerializeToString,
            ),
            'PiiScan': grpc.unary_unary_rpc_method_handler(
                    servicer.PiiScan,
                    request_deserializer=amdi__pb2.PiiScanRequest.FromString,
                    response_serializer=amdi__pb2.PiiScanResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=amdi__pb2.HealthRequest.FromString,
                    response_serializer=amdi__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'amdi.v1.DocumentIntelligence', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('amdi.v1.DocumentIntelligence', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentIntelligence:
    """=============================================================================
    ============================== SERVICES =====================================
    =============================================================================

    """

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/amdi.v1.DocumentIntelligence/Upload',
            amdi__pb2.UploadRequest.SerializeToString,
            amdi__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amdi.v1.DocumentIntelligence/GetJob',
            amdi__pb2.GetJobRequest.SerializeToString,
            amdi__pb2.Job.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amdi.v1.DocumentIntelligence/CancelJob',
            amdi__pb2.CancelJobRequest.SerializeToString,
            amdi__pb2.Job.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amdi.v1.DocumentIntelligence/ListJobs',
            amdi__pb2.ListJobsRequest.SerializeToString,
            amdi__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJobEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/amdi.v1.DocumentIntelligence/StreamJobEvents',
            amdi__pb2.GetJobRequest.SerializeToString,
            amdi__pb2.JobEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amdi.v1.DocumentIntelligence/Query',
            amdi__pb2.QueryRequest.SerializeToString,
            amdi__pb2.RetrievalResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportTokenOptimized(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amdi.v1.DocumentIntelligence/ExportTokenOptimized',
            amdi__pb2.ExportRequest.SerializeToString,
            amdi__pb2.TokenOptimizedExport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PiiScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amdi.v1.DocumentIntelligence/PiiScan',
            amdi__pb2.PiiScanRequest.SerializeToString,
            amdi__pb2.PiiScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amdi.v1.DocumentIntelligence/Health',
            amdi__pb2.HealthRequest.SerializeToString,
            amdi__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
