"""
Verification Engine Orchestrator
================================

Orchestrates the verification process, calling all sub-verifiers and aggregating
metrics into a unified VerificationReport.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from .exceptions import ConfidenceThresholdError, HallucinationDetectedError
from .citation_verifier import CitationVerifier
from .fact_verifier import FactVerifier
from .confidence_scorer import ConfidenceScorer
from .hallucination_detector import HallucinationDetector
from .consistency_checker import ConsistencyChecker
from .source_verifier import SourceVerifier
from .verification_report import VerificationReportData, VerificationMetrics


class VerificationReport:
    """Report generated by the Verification Engine."""

    def __init__(self, data: VerificationReportData) -> None:
        self.data = data

    @property
    def is_valid(self) -> bool:
        return self.data.passed

    @property
    def overall_confidence(self) -> float:
        return self.data.metrics.composite_confidence

    def to_dict(self) -> dict:
        return self.data.to_dict()

    def raise_for_status(self) -> None:
        """Raise exception if verification failed."""
        if not self.data.passed:
            if "high_hallucination_risk" in self.data.issues or any(
                i.get("severity", 0) > 0.8
                for i in self.data.hallucination_result.to_dict().get("indicators", [])
            ):
                raise HallucinationDetectedError("Hallucination detected with high severity.")
            raise ConfidenceThresholdError(
                f"Verification failed: composite confidence {self.overall_confidence:.3f} "
                f"or threshold checks failed. Issues: {self.data.issues}"
            )


class VerificationEngine:
    """
    Main orchestrator for post-response verification.
    """

    def __init__(
        self,
        min_confidence: float = 0.7,
        strict_citations: bool = False,
        fuzzy_threshold: float = 0.75,
        kb: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.min_confidence = min_confidence
        self.citation_verifier = CitationVerifier(strict=strict_citations, fuzzy_threshold=fuzzy_threshold)
        self.fact_verifier = FactVerifier(knowledge_base=kb, fuzzy_threshold=fuzzy_threshold)
        self.confidence_scorer = ConfidenceScorer(passing_threshold=min_confidence)
        self.hallucination_detector = HallucinationDetector()
        self.consistency_checker = ConsistencyChecker()
        self.source_verifier = SourceVerifier()

    def verify(
        self,
        response_text: str,
        source_documents: Dict[str, Any],
        knowledge_base: Optional[Dict[str, Any]] = None,
        explained_variance: float = 1.0,
    ) -> VerificationReport:
        """
        Verify the response text against source documents and knowledge base.
        """
        # 1. Run all sub-verifiers
        citation_res = self.citation_verifier.verify(response_text, source_documents)

        kb_to_use = knowledge_base if knowledge_base is not None else self.fact_verifier.knowledge_base
        fact_res = self.fact_verifier.verify(response_text, kb_to_use)

        source_res = self.source_verifier.verify(source_documents)

        hallucination_res = self.hallucination_detector.detect(
            response_text,
            source_documents=source_documents,
        )

        consistency_res = self.consistency_checker.check(response_text)

        # 2. Score overall confidence
        confidence_score = self.confidence_scorer.score(
            citation_accuracy=citation_res.accuracy,
            fact_accuracy=fact_res.accuracy,
            hallucination_rate=hallucination_res.hallucination_rate,
            source_reliability=source_res.source_reliability,
            explained_variance=explained_variance,
        )

        # 3. Compile issues
        issues: List[str] = []
        issues.extend(citation_res.issues)
        issues.extend(fact_res.issues)
        issues.extend(source_res.issues)
        issues.extend(hallucination_res.issues)
        for issue_dict in consistency_res.issues:
            issues.append(f"consistency_{issue_dict.get('type')}:{issue_dict.get('description')}")

        if confidence_score.overall < self.min_confidence:
            issues.append("low_composite_confidence")

        # passed condition: confidence threshold check and hallucination threshold check
        passed = (confidence_score.overall >= self.min_confidence) and (hallucination_res.hallucination_rate <= 0.3)

        # 4. Construct report
        metrics = VerificationMetrics(
            citation_accuracy=citation_res.accuracy,
            fact_accuracy=fact_res.accuracy,
            hallucination_rate=hallucination_res.hallucination_rate,
            consistency_score=consistency_res.consistency_score,
            source_reliability=source_res.source_reliability,
            composite_confidence=confidence_score.overall,
        )

        report_data = VerificationReportData(
            response_text=response_text,
            metrics=metrics,
            citation_result=citation_res,
            fact_result=fact_res,
            hallucination_result=hallucination_res,
            consistency_result=consistency_res,
            source_result=source_res,
            passed=passed,
            grade=confidence_score.grade,
            issues=issues,
        )

        return VerificationReport(report_data)
