apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-api-pdb
  labels: {{- include "amdi.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {app: amdi, role: api}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-worker-pdb
  labels: {{- include "amdi.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {app: amdi, role: worker}
