apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt
  labels: {{- include "amdi.labels" . | nindent 4 }}
type: Opaque
stringData:
  AMDI_JWT_SECRET: {{ required "set AMDI_JWT_SECRET" .Values.jwtSecret | quote }}
