apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels: {{- include "amdi.labels" . | nindent 4 }}
spec:
  selector: {app: amdi, role: api}
  ports:
    - {name: http,    port: 8000, targetPort: 8000}
    - {name: metrics, port: 9090, targetPort: 9090}
