"""
AEGIS-DocIntel / AMDI-OS — Core System Module
"""

from src.models.document_object import DocumentObject, DocumentFormat, MAGIC, EXT_MAP
from src.core.normalized_document import (
    NormalizedDocument,
    NormalizedPage,
    NormalizedBlock,
    BlockType,
    BoundingBox as LegacyBoundingBox,
)
from src.core.geometric_element import make_element, GeometricElement, ElementType
from src.core.document_state import (
    DocumentState,
    PhysicalLayer,
    SemanticLayer,
    GraphLayer,
    RecurrenceLayer,
    SpectralLayer,
    MatrixLayer,
    TopologyLayer,
    InfoPhysicsLayer,
    HypergraphLayer,
    TelemetryLayer,
    BoundingBox,
    PageInfo,
    LayoutElement,
    ReadingOrderDAG,
    TopicDistribution,
    Keyphrase,
    Entity,
    GraphNode,
    GraphEdge,
    RepeatedPattern,
    SpectralCluster,
    TableData,
    PersistenceInterval,
    HyperEdge,
    PipelineStageRecord,
)

__all__ = [
    "DocumentObject",
    "DocumentFormat",
    "NormalizedDocument",
    "NormalizedPage",
    "NormalizedBlock",
    "BlockType",
    "LegacyBoundingBox",
    "make_element",
    "GeometricElement",
    "ElementType",
    "DocumentState",
    "PhysicalLayer",
    "SemanticLayer",
    "GraphLayer",
    "RecurrenceLayer",
    "SpectralLayer",
    "MatrixLayer",
    "TopologyLayer",
    "InfoPhysicsLayer",
    "HypergraphLayer",
    "TelemetryLayer",
    "BoundingBox",
    "PageInfo",
    "LayoutElement",
    "ReadingOrderDAG",
    "TopicDistribution",
    "Keyphrase",
    "Entity",
    "GraphNode",
    "GraphEdge",
    "RepeatedPattern",
    "SpectralCluster",
    "TableData",
    "PersistenceInterval",
    "HyperEdge",
    "PipelineStageRecord",
]
